VM_MEMORY=2048
VM_CORES=1

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'

  config.vm.provider :virtualbox do |v, override|
    v.memory = VM_MEMORY
    v.cpus = VM_CORES

    required_plugins = %w(vagrant-vbguest)
    required_plugins.each do |plugin|
      system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
    end
  end

  config.vm.provision 'shell' do |s|
    s.inline = 'echo Setting up machine name'
    config.vm.provider :virtualbox do |v, override|
      v.name = "qemu-arm-kernel"
    end
  end

  config.vm.provision 'shell', privileged: true, inline:
    "sed -i 's|deb http://us.archive.ubuntu.com/ubuntu/|deb mirror://mirrors.ubuntu.com/mirrors.txt|g' /etc/apt/sources.list
    dpkg --add-architecture i386
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get -s -y dist-upgrade
    apt-get -y install build-essential libncurses5-dev \
        git flex bison gcc-arm-linux-gnueabihf libc6:i386 emacs-nox
    apt-get -y autoremove
    apt-get -y clean
    update-locale LC_ALL=C
    echo '---'
    echo 'see instructions in README.md to build QEMU ARM kernel'"
  end
